function allowMissingField(field) {
    return field.allowNull
            || field.autoIncrement
            || field.defaultValue != null
            || field._autoGenerated
            ? true : false;
}

function validateQuery(fields, whitelisted = []) {
    return (req, res, next) => {
        for(const field of Object.keys(fields)) {
            if(!req.body[field] && !allowMissingField(fields[field]) && !whitelisted.includes(field)) {
                    return res.status(400).send(`${field} is missing.`);
            }
        }
        next();
    };
}

module.exports.validateQuery = validateQuery;
